# Stage 1: Build the Angular app
FROM node:latest as build
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install
COPY . .
RUN npm run build

# Stage 2: Serve the app using nginx
FROM nginx:alpine
COPY --from=build /app/dist/frontend-pepper /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

