@startuml
actor "User" as user

usecase "Upload Image" as uploadImage
usecase "View Images" as viewImages
usecase "Play Game" as playGame
usecase "View Score" as viewScore
usecase "Set Game Type" as setGameType

user --> uploadImage
user --> viewImages
user --> playGame
user --> viewScore

actor "Admin" as admin
admin --> setGameType

uploadImage --> (Manage Images)
viewImages --> (Manage Images)
playGame --> (Record Game Score)
viewScore --> (View Game Score)
setGameType --> (Manage Game Type)

@enduml